import numpy as np
arr = np.array([10, 23, 39, 44, 56])
print("Original Array:", arr)
print("First element:", arr[0])
print("Last element:", arr[-1])
print("Slice from index 1 to 3:", arr[1:4])
print("Array + 5:", arr + 5)
print("Array - 5:", arr - 5)
print("Array * 2:", arr * 2)
print("Array / 2:", arr / 2)
print("Mean of elements:", np.mean(arr))
print("Array squared:", arr ** 2)
print("Sum of elements:", np.sum(arr))
print("Median of elements:", np.median(arr))
print("Maximum element:", np.max(arr))
print("Minimum element:", np.min(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))
print("Index of max element:", np.argmax(arr))
print("Index of min element:", np.argmin(arr))
print("Length of array:", len(arr))
print("Length of array:", len(arr))
print("Shape of array:", arr.shape)
print("Data type of array:", arr.dtype)
